apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    app.kubernetes.io/name: deathstar
    class: deathstar
    org: empire
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

